plugin: aws_ec2
regions:
  - us-east-1

filters:
   instance-state-name: running
   vpc-id: vpc-04573f9e4812f9e06
keyed_groups:
    - key: tags.Tier
      separator: ''
#strict_permissions: False

compose:
    ansible_host: private_ip_address
